const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_FRIEND_REQUEST = "NEW_FRIEND_REQUEST";
const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
const REJECT_FRIEND_REQUEST = "REJECT_FRIEND_REQUEST";
const FRIEND_REQUEST_SENT = "FRIEND_REQUEST_SENT";
const FRIEND_REQUEST_ACCEPTED = "FRIEND_REQUEST_ACCEPTED";
const FRIEND_REQUEST_REJECTED = "FRIEND_REQUEST_REJECTED";
const CANCEL_FRIEND_REQUEST = "CANCEL_FRIEND_REQUEST";
const REFETCH_FRIEND_REQUESTS = "REFETCH_FRIEND_REQUESTS";
const FRIEND_REQUEST_CANCELLED = "FRIEND_REQUEST_CANCELLED";
const REFETCH_SENT_REQUESTS = "REFETCH_SENT_REQUESTS";
const FRIEND_CAME_ONLINE = "FRIEND_CAME_ONLINE";
const FRIEND_WENT_OFFLINE = "FRIEND_WENT_OFFLINE";
const MESSAGE_DELIVERED = "MESSAGE_DELIVERED";
const READ_MESSAGE = "READ_MESSAGE";
const FRIEND_READ_MESSAGE = "FRIEND_READ_MESSAGE";
const START_CHAT = "START_CHAT";
const OPEN_CHAT = "OPEN_CHAT";
const TYPING = "TYPING";
const STOP_TYPING = "STOP_TYPING";

module.exports = {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_FRIEND_REQUEST,
  SEND_FRIEND_REQUEST,
  ACCEPT_FRIEND_REQUEST,
  REJECT_FRIEND_REQUEST,
  FRIEND_REQUEST_SENT,
  FRIEND_REQUEST_ACCEPTED,
  FRIEND_REQUEST_REJECTED,
  CANCEL_FRIEND_REQUEST,
  REFETCH_FRIEND_REQUESTS,
  FRIEND_REQUEST_CANCELLED,
  REFETCH_SENT_REQUESTS,
  FRIEND_CAME_ONLINE,
  FRIEND_WENT_OFFLINE,
  MESSAGE_DELIVERED,
  READ_MESSAGE,
  FRIEND_READ_MESSAGE,
  START_CHAT,
  OPEN_CHAT,
  TYPING,
  STOP_TYPING,
};
